[build]
  command = 'npm run build'
  publish = 'public/'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"  
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
  